version: 0.2
phases:
 install:
   commands:
     - echo "Install backend"
     - cd backend
     - |
        if [ ! -d "flyway-5.2.4" ]; then
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz | tar xvz
          ln -sf '../libjsig.so' flyway-5.2.4/jre/lib/amd64/server/libjsig.so # Workaround for https://github.com/flyway/flyway/issues/2312
        fi
     - npm install
     - echo "Install frontend"
     - cd ../frontend/turo-app
     - npm install
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "Deploy backend"
     - cd ../../backend
     - env NODE_ENV=production npx serverless deploy -v
     - echo "Migrate database"
     - flyway-5.2.4/flyway migrate -url="jdbc:postgresql://turodb.ccahsd6rorzm.eu-west-1.rds.amazonaws.com:5432/turo_db" -user="db_admin" -password="$(aws ssm get-parameter --name db_instance_password --with-decryption --output text --query Parameter.Value)" -locations=filesystem:../sql
     - echo "Build React app"
     - cd ../frontend/turo-app
     - env NODE_ENV=production npm run build
     - aws s3 sync build s3://turo-app
 post_build:
   commands:
     - echo "post_build step"
cache:
  paths:
    - 'frontend/turo-app/node_modules/**/*'
    - 'backend/flyway-5.2.4/**/*'
