version: 0.2
phases:
 install:
   commands:
     - cd backend
     - echo "install step"
     - npm install serverless
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - serverless deploy -v
 post_build:
   commands:
     - echo "post_build step"
